// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"blogGo/src/model"
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newTodoInfo(db *gorm.DB, opts ...gen.DOOption) todoInfo {
	_todoInfo := todoInfo{}

	_todoInfo.todoInfoDo.UseDB(db, opts...)
	_todoInfo.todoInfoDo.UseModel(&model.TodoInfo{})

	tableName := _todoInfo.todoInfoDo.TableName()
	_todoInfo.ALL = field.NewAsterisk(tableName)
	_todoInfo.ID = field.NewUint(tableName, "id")
	_todoInfo.CreatedAt = field.NewTime(tableName, "created_at")
	_todoInfo.UpdatedAt = field.NewTime(tableName, "updated_at")
	_todoInfo.DeletedAt = field.NewField(tableName, "deleted_at")
	_todoInfo.Title = field.NewString(tableName, "title")
	_todoInfo.Content = field.NewString(tableName, "content")
	_todoInfo.Status = field.NewInt(tableName, "status")
	_todoInfo.CreatedBy = field.NewString(tableName, "created_by")
	_todoInfo.UpdatedBy = field.NewString(tableName, "updated_by")

	_todoInfo.fillFieldMap()

	return _todoInfo
}

type todoInfo struct {
	todoInfoDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	Title     field.String
	Content   field.String
	Status    field.Int
	CreatedBy field.String
	UpdatedBy field.String

	fieldMap map[string]field.Expr
}

func (t todoInfo) Table(newTableName string) *todoInfo {
	t.todoInfoDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t todoInfo) As(alias string) *todoInfo {
	t.todoInfoDo.DO = *(t.todoInfoDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *todoInfo) updateTableName(table string) *todoInfo {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewUint(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.DeletedAt = field.NewField(table, "deleted_at")
	t.Title = field.NewString(table, "title")
	t.Content = field.NewString(table, "content")
	t.Status = field.NewInt(table, "status")
	t.CreatedBy = field.NewString(table, "created_by")
	t.UpdatedBy = field.NewString(table, "updated_by")

	t.fillFieldMap()

	return t
}

func (t *todoInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *todoInfo) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 9)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt
	t.fieldMap["title"] = t.Title
	t.fieldMap["content"] = t.Content
	t.fieldMap["status"] = t.Status
	t.fieldMap["created_by"] = t.CreatedBy
	t.fieldMap["updated_by"] = t.UpdatedBy
}

func (t todoInfo) clone(db *gorm.DB) todoInfo {
	t.todoInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t todoInfo) replaceDB(db *gorm.DB) todoInfo {
	t.todoInfoDo.ReplaceDB(db)
	return t
}

type todoInfoDo struct{ gen.DO }

type ITodoInfoDo interface {
	gen.SubQuery
	Debug() ITodoInfoDo
	WithContext(ctx context.Context) ITodoInfoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITodoInfoDo
	WriteDB() ITodoInfoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITodoInfoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITodoInfoDo
	Not(conds ...gen.Condition) ITodoInfoDo
	Or(conds ...gen.Condition) ITodoInfoDo
	Select(conds ...field.Expr) ITodoInfoDo
	Where(conds ...gen.Condition) ITodoInfoDo
	Order(conds ...field.Expr) ITodoInfoDo
	Distinct(cols ...field.Expr) ITodoInfoDo
	Omit(cols ...field.Expr) ITodoInfoDo
	Join(table schema.Tabler, on ...field.Expr) ITodoInfoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITodoInfoDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITodoInfoDo
	Group(cols ...field.Expr) ITodoInfoDo
	Having(conds ...gen.Condition) ITodoInfoDo
	Limit(limit int) ITodoInfoDo
	Offset(offset int) ITodoInfoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITodoInfoDo
	Unscoped() ITodoInfoDo
	Create(values ...*model.TodoInfo) error
	CreateInBatches(values []*model.TodoInfo, batchSize int) error
	Save(values ...*model.TodoInfo) error
	First() (*model.TodoInfo, error)
	Take() (*model.TodoInfo, error)
	Last() (*model.TodoInfo, error)
	Find() ([]*model.TodoInfo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TodoInfo, err error)
	FindInBatches(result *[]*model.TodoInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TodoInfo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITodoInfoDo
	Assign(attrs ...field.AssignExpr) ITodoInfoDo
	Joins(fields ...field.RelationField) ITodoInfoDo
	Preload(fields ...field.RelationField) ITodoInfoDo
	FirstOrInit() (*model.TodoInfo, error)
	FirstOrCreate() (*model.TodoInfo, error)
	FindByPage(offset int, limit int) (result []*model.TodoInfo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITodoInfoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t todoInfoDo) Debug() ITodoInfoDo {
	return t.withDO(t.DO.Debug())
}

func (t todoInfoDo) WithContext(ctx context.Context) ITodoInfoDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t todoInfoDo) ReadDB() ITodoInfoDo {
	return t.Clauses(dbresolver.Read)
}

func (t todoInfoDo) WriteDB() ITodoInfoDo {
	return t.Clauses(dbresolver.Write)
}

func (t todoInfoDo) Session(config *gorm.Session) ITodoInfoDo {
	return t.withDO(t.DO.Session(config))
}

func (t todoInfoDo) Clauses(conds ...clause.Expression) ITodoInfoDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t todoInfoDo) Returning(value interface{}, columns ...string) ITodoInfoDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t todoInfoDo) Not(conds ...gen.Condition) ITodoInfoDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t todoInfoDo) Or(conds ...gen.Condition) ITodoInfoDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t todoInfoDo) Select(conds ...field.Expr) ITodoInfoDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t todoInfoDo) Where(conds ...gen.Condition) ITodoInfoDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t todoInfoDo) Order(conds ...field.Expr) ITodoInfoDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t todoInfoDo) Distinct(cols ...field.Expr) ITodoInfoDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t todoInfoDo) Omit(cols ...field.Expr) ITodoInfoDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t todoInfoDo) Join(table schema.Tabler, on ...field.Expr) ITodoInfoDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t todoInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITodoInfoDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t todoInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) ITodoInfoDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t todoInfoDo) Group(cols ...field.Expr) ITodoInfoDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t todoInfoDo) Having(conds ...gen.Condition) ITodoInfoDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t todoInfoDo) Limit(limit int) ITodoInfoDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t todoInfoDo) Offset(offset int) ITodoInfoDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t todoInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITodoInfoDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t todoInfoDo) Unscoped() ITodoInfoDo {
	return t.withDO(t.DO.Unscoped())
}

func (t todoInfoDo) Create(values ...*model.TodoInfo) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t todoInfoDo) CreateInBatches(values []*model.TodoInfo, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t todoInfoDo) Save(values ...*model.TodoInfo) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t todoInfoDo) First() (*model.TodoInfo, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TodoInfo), nil
	}
}

func (t todoInfoDo) Take() (*model.TodoInfo, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TodoInfo), nil
	}
}

func (t todoInfoDo) Last() (*model.TodoInfo, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TodoInfo), nil
	}
}

func (t todoInfoDo) Find() ([]*model.TodoInfo, error) {
	result, err := t.DO.Find()
	return result.([]*model.TodoInfo), err
}

func (t todoInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TodoInfo, err error) {
	buf := make([]*model.TodoInfo, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t todoInfoDo) FindInBatches(result *[]*model.TodoInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t todoInfoDo) Attrs(attrs ...field.AssignExpr) ITodoInfoDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t todoInfoDo) Assign(attrs ...field.AssignExpr) ITodoInfoDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t todoInfoDo) Joins(fields ...field.RelationField) ITodoInfoDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t todoInfoDo) Preload(fields ...field.RelationField) ITodoInfoDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t todoInfoDo) FirstOrInit() (*model.TodoInfo, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TodoInfo), nil
	}
}

func (t todoInfoDo) FirstOrCreate() (*model.TodoInfo, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TodoInfo), nil
	}
}

func (t todoInfoDo) FindByPage(offset int, limit int) (result []*model.TodoInfo, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t todoInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t todoInfoDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t todoInfoDo) Delete(models ...*model.TodoInfo) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *todoInfoDo) withDO(do gen.Dao) *todoInfoDo {
	t.DO = *do.(*gen.DO)
	return t
}
