// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"blogGo/src/model"
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newTodoMessage(db *gorm.DB, opts ...gen.DOOption) todoMessage {
	_todoMessage := todoMessage{}

	_todoMessage.todoMessageDo.UseDB(db, opts...)
	_todoMessage.todoMessageDo.UseModel(&model.TodoMessage{})

	tableName := _todoMessage.todoMessageDo.TableName()
	_todoMessage.ALL = field.NewAsterisk(tableName)
	_todoMessage.ID = field.NewUint(tableName, "id")
	_todoMessage.CreatedAt = field.NewTime(tableName, "created_at")
	_todoMessage.UpdatedAt = field.NewTime(tableName, "updated_at")
	_todoMessage.DeletedAt = field.NewField(tableName, "deleted_at")
	_todoMessage.MailTo = field.NewString(tableName, "mail_to")
	_todoMessage.Title = field.NewString(tableName, "title")
	_todoMessage.Content = field.NewString(tableName, "content")
	_todoMessage.Status = field.NewBool(tableName, "status")
	_todoMessage.CreatedBy = field.NewString(tableName, "created_by")
	_todoMessage.UpdatedBy = field.NewString(tableName, "updated_by")

	_todoMessage.fillFieldMap()

	return _todoMessage
}

type todoMessage struct {
	todoMessageDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	MailTo    field.String
	Title     field.String
	Content   field.String
	Status    field.Bool
	CreatedBy field.String
	UpdatedBy field.String

	fieldMap map[string]field.Expr
}

func (t todoMessage) Table(newTableName string) *todoMessage {
	t.todoMessageDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t todoMessage) As(alias string) *todoMessage {
	t.todoMessageDo.DO = *(t.todoMessageDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *todoMessage) updateTableName(table string) *todoMessage {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewUint(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.DeletedAt = field.NewField(table, "deleted_at")
	t.MailTo = field.NewString(table, "mail_to")
	t.Title = field.NewString(table, "title")
	t.Content = field.NewString(table, "content")
	t.Status = field.NewBool(table, "status")
	t.CreatedBy = field.NewString(table, "created_by")
	t.UpdatedBy = field.NewString(table, "updated_by")

	t.fillFieldMap()

	return t
}

func (t *todoMessage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *todoMessage) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 10)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt
	t.fieldMap["mail_to"] = t.MailTo
	t.fieldMap["title"] = t.Title
	t.fieldMap["content"] = t.Content
	t.fieldMap["status"] = t.Status
	t.fieldMap["created_by"] = t.CreatedBy
	t.fieldMap["updated_by"] = t.UpdatedBy
}

func (t todoMessage) clone(db *gorm.DB) todoMessage {
	t.todoMessageDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t todoMessage) replaceDB(db *gorm.DB) todoMessage {
	t.todoMessageDo.ReplaceDB(db)
	return t
}

type todoMessageDo struct{ gen.DO }

type ITodoMessageDo interface {
	gen.SubQuery
	Debug() ITodoMessageDo
	WithContext(ctx context.Context) ITodoMessageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITodoMessageDo
	WriteDB() ITodoMessageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITodoMessageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITodoMessageDo
	Not(conds ...gen.Condition) ITodoMessageDo
	Or(conds ...gen.Condition) ITodoMessageDo
	Select(conds ...field.Expr) ITodoMessageDo
	Where(conds ...gen.Condition) ITodoMessageDo
	Order(conds ...field.Expr) ITodoMessageDo
	Distinct(cols ...field.Expr) ITodoMessageDo
	Omit(cols ...field.Expr) ITodoMessageDo
	Join(table schema.Tabler, on ...field.Expr) ITodoMessageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITodoMessageDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITodoMessageDo
	Group(cols ...field.Expr) ITodoMessageDo
	Having(conds ...gen.Condition) ITodoMessageDo
	Limit(limit int) ITodoMessageDo
	Offset(offset int) ITodoMessageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITodoMessageDo
	Unscoped() ITodoMessageDo
	Create(values ...*model.TodoMessage) error
	CreateInBatches(values []*model.TodoMessage, batchSize int) error
	Save(values ...*model.TodoMessage) error
	First() (*model.TodoMessage, error)
	Take() (*model.TodoMessage, error)
	Last() (*model.TodoMessage, error)
	Find() ([]*model.TodoMessage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TodoMessage, err error)
	FindInBatches(result *[]*model.TodoMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TodoMessage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITodoMessageDo
	Assign(attrs ...field.AssignExpr) ITodoMessageDo
	Joins(fields ...field.RelationField) ITodoMessageDo
	Preload(fields ...field.RelationField) ITodoMessageDo
	FirstOrInit() (*model.TodoMessage, error)
	FirstOrCreate() (*model.TodoMessage, error)
	FindByPage(offset int, limit int) (result []*model.TodoMessage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITodoMessageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t todoMessageDo) Debug() ITodoMessageDo {
	return t.withDO(t.DO.Debug())
}

func (t todoMessageDo) WithContext(ctx context.Context) ITodoMessageDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t todoMessageDo) ReadDB() ITodoMessageDo {
	return t.Clauses(dbresolver.Read)
}

func (t todoMessageDo) WriteDB() ITodoMessageDo {
	return t.Clauses(dbresolver.Write)
}

func (t todoMessageDo) Session(config *gorm.Session) ITodoMessageDo {
	return t.withDO(t.DO.Session(config))
}

func (t todoMessageDo) Clauses(conds ...clause.Expression) ITodoMessageDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t todoMessageDo) Returning(value interface{}, columns ...string) ITodoMessageDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t todoMessageDo) Not(conds ...gen.Condition) ITodoMessageDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t todoMessageDo) Or(conds ...gen.Condition) ITodoMessageDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t todoMessageDo) Select(conds ...field.Expr) ITodoMessageDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t todoMessageDo) Where(conds ...gen.Condition) ITodoMessageDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t todoMessageDo) Order(conds ...field.Expr) ITodoMessageDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t todoMessageDo) Distinct(cols ...field.Expr) ITodoMessageDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t todoMessageDo) Omit(cols ...field.Expr) ITodoMessageDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t todoMessageDo) Join(table schema.Tabler, on ...field.Expr) ITodoMessageDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t todoMessageDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITodoMessageDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t todoMessageDo) RightJoin(table schema.Tabler, on ...field.Expr) ITodoMessageDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t todoMessageDo) Group(cols ...field.Expr) ITodoMessageDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t todoMessageDo) Having(conds ...gen.Condition) ITodoMessageDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t todoMessageDo) Limit(limit int) ITodoMessageDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t todoMessageDo) Offset(offset int) ITodoMessageDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t todoMessageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITodoMessageDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t todoMessageDo) Unscoped() ITodoMessageDo {
	return t.withDO(t.DO.Unscoped())
}

func (t todoMessageDo) Create(values ...*model.TodoMessage) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t todoMessageDo) CreateInBatches(values []*model.TodoMessage, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t todoMessageDo) Save(values ...*model.TodoMessage) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t todoMessageDo) First() (*model.TodoMessage, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TodoMessage), nil
	}
}

func (t todoMessageDo) Take() (*model.TodoMessage, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TodoMessage), nil
	}
}

func (t todoMessageDo) Last() (*model.TodoMessage, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TodoMessage), nil
	}
}

func (t todoMessageDo) Find() ([]*model.TodoMessage, error) {
	result, err := t.DO.Find()
	return result.([]*model.TodoMessage), err
}

func (t todoMessageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TodoMessage, err error) {
	buf := make([]*model.TodoMessage, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t todoMessageDo) FindInBatches(result *[]*model.TodoMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t todoMessageDo) Attrs(attrs ...field.AssignExpr) ITodoMessageDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t todoMessageDo) Assign(attrs ...field.AssignExpr) ITodoMessageDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t todoMessageDo) Joins(fields ...field.RelationField) ITodoMessageDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t todoMessageDo) Preload(fields ...field.RelationField) ITodoMessageDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t todoMessageDo) FirstOrInit() (*model.TodoMessage, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TodoMessage), nil
	}
}

func (t todoMessageDo) FirstOrCreate() (*model.TodoMessage, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TodoMessage), nil
	}
}

func (t todoMessageDo) FindByPage(offset int, limit int) (result []*model.TodoMessage, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t todoMessageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t todoMessageDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t todoMessageDo) Delete(models ...*model.TodoMessage) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *todoMessageDo) withDO(do gen.Dao) *todoMessageDo {
	t.DO = *do.(*gen.DO)
	return t
}
